services:
  couchdb:
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/data:/opt/couchdb/data

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./flask:/app
    environment:
      - PYTHONPATH=/app

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app
    command: ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

  #websockets:
    #build:
      #context: ./websockets
      #dockerfile: Dockerfile.websockets
    #ports:
      #- "5004:5000"
    #volumes:
      #- ./websockets:/app_websockets
