version: '3.7'
services:
  couchdb:
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/data:/opt/couchdb/data

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
